### ISSUE TITLE
There are no demos :-(

### ISSUE THREAD

**Issue by arichiv** [MSuite/ios-demos#1]

**Comment by ottosipe** [comment]
Ha ha. I just init the repo for Andrew. Demos to come!

**Comment by andrewrauh** [comment]
adding some later today. 
stay tuned.

**Comment by arichiv** [comment]
![picard-yes](https://f.cloud.github.com/assets/666538/322618/5ee836fa-9a63-11e2-9cd0-8fa6345c3c5a.jpg)
